name: GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to use

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: cp -r first_resource/html_test.html docs
